Repository PRIYANSHU2026/DataSentience-AIML, pull requests merged in 2025-07, with the labels that each got.

#177 Insurance predictor
  src/Financial Analysis/Market Analysis/insurance predictor/README.md
  src/Financial Analysis/Market Analysis/insurance predictor/assets/image.png
  src/Financial Analysis/Market Analysis/insurance predictor/data/insurance.csv
  src/Financial Analysis/Market Analysis/insurance predictor/predict.py
  src/Financial Analysis/Market Analysis/insurance predictor/preprocess.py
  src/Financial Analysis/Market Analysis/insurance predictor/train.py
Labels: SSOC S4, INTERMEDIATE

#184 ui stroke prediction
  src/Healthcare/Health Monitoring/stroke-prediction/README.md
  src/Healthcare/Health Monitoring/stroke-prediction/assets/Screenshot_3-7-2025_144231_localhost.jpeg
  src/Healthcare/Health Monitoring/stroke-prediction/predict.py
Labels: SSOC S4, INTERMEDIATE

#197 Lung cancer prediction
  src/Healthcare/Disease Detection/lung-cancer-prediction/README.md
  src/Healthcare/Disease Detection/lung-cancer-prediction/assets/image.png
  src/Healthcare/Disease Detection/lung-cancer-prediction/cleaned_data.csv
  src/Healthcare/Disease Detection/lung-cancer-prediction/data/survey lung cancer.csv
  src/Healthcare/Disease Detection/lung-cancer-prediction/predict.py
  src/Healthcare/Disease Detection/lung-cancer-prediction/preprocess.py
  src/Healthcare/Disease Detection/lung-cancer-prediction/train_model.py
Labels: SSOC S4, INTERMEDIATE

#250 feat(ui): Transform Credit Card Checker with Professional Interface & Advanced Analytics
  src/Financial Analysis/Credit Card Eligibility Checker/READ.md
  src/Financial Analysis/Credit Card Eligibility Checker/Scripts/eligibility_logic.py
  src/Financial Analysis/Credit Card Eligibility Checker/Scripts/streamlit_app.py
  src/Financial Analysis/Credit Card Eligibility Checker/requirements.txt
Labels: level 3

#257 Body Fat Prediction System
  src/Healthcare/Health Monitoring/Body Fat Prediction/.gitignore
  src/Healthcare/Health Monitoring/Body Fat Prediction/README.md
  src/Healthcare/Health Monitoring/Body Fat Prediction/app.py
  src/Healthcare/Health Monitoring/Body Fat Prediction/bodyfat.csv
  src/Healthcare/Health Monitoring/Body Fat Prediction/model.ipynb
  src/Healthcare/Health Monitoring/Body Fat Prediction/model/linear_regression.lb
Labels: gssoc25, level 2
