Repository PRIYANSHU2026/DataSentience-AIML, pull requests merged in 2025-08, with the labels that each got.

#328 feat: Add Maternal Health Risk Prediction project
  src/Healthcare/Health Monitoring/Maternal Health Risk Predictor/Maternal Health Risk Data Set.csv
  src/Healthcare/Health Monitoring/Maternal Health Risk Predictor/Maternal Health Risk Predictor.ipynb
  src/Healthcare/Health Monitoring/Maternal Health Risk Predictor/README.MD
  src/Healthcare/Health Monitoring/Maternal Health Risk Predictor/app.py
  src/Healthcare/Health Monitoring/Maternal Health Risk Predictor/label_encoder.joblib
  src/Healthcare/Health Monitoring/Maternal Health Risk Predictor/maternal_risk_model.joblib
  src/Healthcare/Health Monitoring/Maternal Health Risk Predictor/requirements.txt
  src/Healthcare/Health Monitoring/Maternal Health Risk Predictor/scaler.joblib
Labels: gssoc25, level 3

#314 add HealthAI Pro
  src/Healthcare/HealthAI Pro/GITHUB_PROJECT_IDEAS.md
  src/Healthcare/HealthAI Pro/README.md
  src/Healthcare/HealthAI Pro/datasets/README.md
  src/Healthcare/HealthAI Pro/datasets/Symptom-severity.csv
  src/Healthcare/HealthAI Pro/datasets/Training.csv
  src/Healthcare/HealthAI Pro/datasets/description.csv
  src/Healthcare/HealthAI Pro/datasets/diets.csv
  src/Healthcare/HealthAI Pro/datasets/medications.csv
  src/Healthcare/HealthAI Pro/datasets/precautions_df.csv
  src/Healthcare/HealthAI Pro/datasets/symtoms_df.csv
  src/Healthcare/HealthAI Pro/datasets/train_mdl.ipynb
  src/Healthcare/HealthAI Pro/datasets/workout_df.csv
  src/Healthcare/HealthAI Pro/instance/README.md
  src/Healthcare/HealthAI Pro/instance/database.db
  src/Healthcare/HealthAI Pro/main.py
  src/Healthcare/HealthAI Pro/static/bg-image.jpg
  src/Healthcare/HealthAI Pro/static/healthcare.jpg
  src/Healthcare/HealthAI Pro/static/home-bgimg.jpg
  src/Healthcare/HealthAI Pro/static/logo.jpg
  src/Healthcare/HealthAI Pro/templates/about.html
  src/Healthcare/HealthAI Pro/templates/blog.html
  src/Healthcare/HealthAI Pro/templates/contact.html
  src/Healthcare/HealthAI Pro/templates/dashboard.html
  src/Healthcare/HealthAI Pro/templates/diagnosis.html
  src/Healthcare/HealthAI Pro/templates/footer.html
  src/Healthcare/HealthAI Pro/templates/index.html
  src/Healthcare/HealthAI Pro/templates/layout.html
  src/Healthcare/HealthAI Pro/templates/login.html
  src/Healthcare/HealthAI Pro/templates/profile.html
  src/Healthcare/HealthAI Pro/templates/register.html
Labels: SSoC25

#348 Pull request of EDA and perform modelling
  src/Machine Learning Techniques/EDA-and-Perform-Modelling-on-Ionosphere-Dataset-main/EDA and Perform modelling on Ionosphere dataset.ipynb
  src/Machine Learning Techniques/EDA-and-Perform-Modelling-on-Ionosphere-Dataset-main/Ionosphere.csv
  src/Machine Learning Techniques/EDA-and-Perform-Modelling-on-Ionosphere-Dataset-main/README.md
Labels: SSoC25, Advanced

#349 Add Credit Score Regressor Using Random Forest
  src/Financial Analysis/Business Analytics/Credit Score Regressor/README.md
  src/Financial Analysis/Business Analytics/Credit Score Regressor/assets/image.png
  src/Financial Analysis/Business Analytics/Credit Score Regressor/data/synthetic_personal_finance_dataset.csv
  src/Financial Analysis/Business Analytics/Credit Score Regressor/predict.py
  src/Financial Analysis/Business Analytics/Credit Score Regressor/preprocess.py
  src/Financial Analysis/Business Analytics/Credit Score Regressor/train.py
Labels: SSoC25, Advanced

#342 Add Delhi NCR Housing Price Predictor
  src/Financial Analysis/Market Analysis/Delhi_housing_predictor/DelhiHousing.ipynb
  src/Financial Analysis/Market Analysis/Delhi_housing_predictor/Readme.md
  src/Financial Analysis/Market Analysis/Delhi_housing_predictor/real_estate_main (1).csv
Labels: gssoc25, level 2

#357 Added Feature in Crop Recommendation System /#305
  src/Agricultural Solutions/Crop Recommendation System/README.md
  src/Agricultural Solutions/Crop Recommendation System/train.py
Labels: gssoc25, level 1

#354 Added new files for recommendation system.
  src/User App Recommendation/Dataset_original.csv
  src/User App Recommendation/EDA.ipynb
  src/User App Recommendation/Preprocessing.ipynb
  src/User App Recommendation/README.md
  src/User App Recommendation/model.ipynb
  src/User App Recommendation/preprocessed_data.csv
Labels: gssoc25, level 2

#361 Add KMeans-Based Car Performance Classifier with Centroid-Based Label Mapping
  src/Financial Analysis/Market Analysis/cars/README.md
  src/Financial Analysis/Market Analysis/cars/assets/image.png
  src/Financial Analysis/Market Analysis/cars/data/labeled_clusters.csv
  src/Financial Analysis/Market Analysis/cars/data/original_dataset.csv
  src/Financial Analysis/Market Analysis/cars/model/cluster_class_mapping.csv
  src/Financial Analysis/Market Analysis/cars/predict.py
  src/Financial Analysis/Market Analysis/cars/preprocess.py
  src/Financial Analysis/Market Analysis/cars/train.py
Labels: SSoC25

#373 Feat/handwritten digit recognition
  src/Machine Learning Techniques/Handwritten_digit_recognition/Handwriten_digit_recognition_.ipynb
  src/Machine Learning Techniques/Handwritten_digit_recognition/readme.md
  src/Machine Learning Techniques/Handwritten_digit_recognition/requirement.txt
Labels: gssoc25, level 2

#420 Added a clean and interactive streamlit web app for heart disease prediction
  src/Healthcare/Disease Detection/Heart Disease Prediction/README.md
  src/Healthcare/Disease Detection/Heart Disease Prediction/app.py
  src/Healthcare/Disease Detection/Heart Disease Prediction/heart-disease-prediction.ipynb
Labels: gssoc25, level 2

#364 Added AgriBot for Agriculture solution
  src/Agricultural Solutions/AgriBot_folder/AgriBot.py
  src/Agricultural Solutions/AgriBot_folder/readme.md
  src/Agricultural Solutions/AgriBot_folder/requirement.txt
Labels: gssoc25

#414 Add Credit Card Fraud Detection Model
  src/Financial Analysis/Credit Card Fraud Detection Model/Readme.md
  src/Financial Analysis/Credit Card Fraud Detection Model/credit card fraud detection model.ipynb
Labels: gssoc25, level 2

#444 Enhanced UI/UX for Waste Classification Model with Eye-Catching Gradient Background
  src/Environmental Monitoring/Waste Classification/requirements.txt
  src/Environmental Monitoring/Waste Classification/web.py
Labels: gssoc25, level 2

#472 Added UPI Fraud Detection project
  src/Financial Analysis/UPI Fraud Detection Model/README.md
  src/Financial Analysis/UPI Fraud Detection Model/notebook.ipynb
  src/Financial Analysis/UPI Fraud Detection Model/requirements.txt
  src/Financial Analysis/UPI Fraud Detection Model/upi_data.csv
Labels: gssoc25, level 2

#470 Add soil classification ml model
  src/Agricultural Solutions/Soil Classification Model/Readme.md
  src/Agricultural Solutions/Soil Classification Model/Soil Classification model.ipynb
Labels: gssoc25, level 2

#523 Added Documentation, Code, Dataset, and Visualizations for Heart Disease Prediction Project
  src/Healthcare/Appling Robust ML model on Healthcare datasets/Appling Robust ML model on Healthcare datasets.md
  src/Healthcare/Appling Robust ML model on Healthcare datasets/Heart_disease_cleveland_new.csv
  src/Healthcare/Appling Robust ML model on Healthcare datasets/images/confusion_matrix.png
  src/Healthcare/Appling Robust ML model on Healthcare datasets/images/correlation_heatmap.png
  src/Healthcare/Appling Robust ML model on Healthcare datasets/images/cross_validation.png
  src/Healthcare/Appling Robust ML model on Healthcare datasets/images/roc_curve.png
  src/Healthcare/Appling Robust ML model on Healthcare datasets/issue_245.ipynb
Labels: gssoc25, Level 2

#507 Pull request of Whatsapp chat analysis
  src/Social Media/Sentiment analysis for Whatsapp/Dataset/WhatsApp (1).csv
  src/Social Media/Sentiment analysis for Whatsapp/Model/Whatsapp_chat_app_ananlysis.ipynb
Labels: gssoc25, Level 2

#518 Add Autism Detection Web App
  src/Healthcare/Autism_Detection/README.md
  src/Healthcare/Autism_Detection/autism-detection.ipynb
  src/Healthcare/Autism_Detection/images/form.png
  src/Healthcare/Autism_Detection/images/result.png
  src/Healthcare/Autism_Detection/requirements.txt
  src/Healthcare/Autism_Detection/web-app/app.py
  src/Healthcare/Autism_Detection/web-app/templates/index.html
  src/Healthcare/Autism_Detection/web-app/templates/result.html
Labels: gssoc25, Level 2

#515 Added Anime Recommender System Using NLP Fixes:Issue #514
  src/Entertainment Industry/Anime Recommender System/Anime_Recommender_System_Content_Based_Filtering.ipynb
  src/Entertainment Industry/Anime Recommender System/Readme.md
Labels: gssoc25, Level 2

#505 Added Matplotlib visualizations Notebook
  src/Agricultural Solutions/Flower_classification_android_app/gradle/wrapper/gradle-wrapper.properties
  src/Machine Learning Techniques/Matplotlib/notebook.ipynb
  src/Machine Learning Techniques/Matplotlib/readme.md
Labels: gssoc25, Level 1

#525 Implement Blood Donor Availability Prediction Model SSoC25
  src/Healthcare/Donor Availability Prediction model/README.md
  src/Healthcare/Donor Availability Prediction model/assets/image.png
  src/Healthcare/Donor Availability Prediction model/data/blood_donor_dataset.csv
  src/Healthcare/Donor Availability Prediction model/predict.py
  src/Healthcare/Donor Availability Prediction model/preprocess.py
  src/Healthcare/Donor Availability Prediction model/train.py
Labels: SSoC25

#532 Pull Request: Meteorite Landings Data Analysis
  src/Machine Learning Techniques/Meteorite Landing Data Analysis/Meteorite.ipynb
  src/Machine Learning Techniques/Meteorite Landing Data Analysis/README.md
Labels: SSoC25

#536 Added Ear Discomfort Predictor (ML Model for Safe Headphone Usage) SSoC25
  src/Healthcare/Ear Discomfort Predictor/README.md
  src/Healthcare/Ear Discomfort Predictor/assets/image.png
  src/Healthcare/Ear Discomfort Predictor/data/Hearing well-being Survey Report.csv
  src/Healthcare/Ear Discomfort Predictor/predict.py
  src/Healthcare/Ear Discomfort Predictor/preprocess.py
  src/Healthcare/Ear Discomfort Predictor/train.py
Labels: SSoC25

#530 Added XGBoost model and interactive streamlit dashboard for asteroid hazard prediction
  src/Machine Learning Techniques/Nasa-Asteroids-Dataset-Analysis/README.md
  src/Machine Learning Techniques/Nasa-Asteroids-Dataset-Analysis/analysis.ipynb
  src/Machine Learning Techniques/Nasa-Asteroids-Dataset-Analysis/app.py
  src/Machine Learning Techniques/Nasa-Asteroids-Dataset-Analysis/requirements.txt
Labels: gssoc25, Level 3
