Repository PRIYANSHU2026/DataSentience-AIML, pull requests merged in 2025-06, with the labels that each got.

#13 Added License
  License.md
Labels: SSOC S4, BEGINNER

#14 Added security.md
  License.md
  Security.md
Labels: SSOC S4, BEGINNER

#16 Image Text Detection using Tesseract OCR
  Optical Detections/Optical character recognition (OCR)/Optical Character Recognition (OCR).ipynb
  Optical Detections/Optical character recognition (OCR)/Output 1 (Resized Image).png
  Optical Detections/Optical character recognition (OCR)/Output 2 (Characters Detected).png
  Optical Detections/Optical character recognition (OCR)/Output 3 (Words Detected).png
  Optical Detections/Optical character recognition (OCR)/README.md
  Optical Detections/Optical character recognition (OCR)/testimg.png
Labels: documentation, enhancement, good first issue, SSOC S4, INTERMEDIATE

#27 feat: Update in README.md for Food Classifier AI in Health AI
  Health AI/Food Classifier AI/README.md
Labels: SSOC S4

#37 Stock sentiment predictor
  Financial AI/stock-sentiment-analyser/README.md
  Financial AI/stock-sentiment-analyser/app.py
  Financial AI/stock-sentiment-analyser/news_scraper.py
  Financial AI/stock-sentiment-analyser/requirements.txt
  Financial AI/stock-sentiment-analyser/sentiment_model.py
  Financial AI/stock-sentiment-analyser/twitter_scrapper.py
  Financial AI/stock-sentiment-analyser/utils.py
Labels: SSOC S4, ADVANCED

#50 Traffic Sign Recognition
  Data Analysis/Traffic Sign Recognition/.idea/.gitignore
  Data Analysis/Traffic Sign Recognition/.idea/Traffic Sign Recognition.iml
  Data Analysis/Traffic Sign Recognition/.idea/inspectionProfiles/Project_Default.xml
  Data Analysis/Traffic Sign Recognition/.idea/inspectionProfiles/profiles_settings.xml
  Data Analysis/Traffic Sign Recognition/.idea/misc.xml
  Data Analysis/Traffic Sign Recognition/.idea/modules.xml
  Data Analysis/Traffic Sign Recognition/.idea/vcs.xml
  Data Analysis/Traffic Sign Recognition/Meta/.~lock.ClassesInformation.ods#
  Data Analysis/Traffic Sign Recognition/Meta/.~lock.ClassesInformationStrong.ods#
  Data Analysis/Traffic Sign Recognition/Readme.md
  Data Analysis/Traffic Sign Recognition/gui.py
  Data Analysis/Traffic Sign Recognition/my_model.h5
  Data Analysis/Traffic Sign Recognition/traffic_classifier.h5
  Data Analysis/Traffic Sign Recognition/traffic_signs.py
Labels: SSOC S4, INTERMEDIATE

#42 Enhanced project README for clarity and structure
  README.md
Labels: SSOC S4, BEGINNER

#45 Added Cancer Prediction Streamlit App under Health AI
  Health AI/Cancer-Prediction/.streamlit/config.toml
  Health AI/Cancer-Prediction/Live_Link.txt
  Health AI/Cancer-Prediction/README.md
  Health AI/Cancer-Prediction/app.py
  Health AI/Cancer-Prediction/application.png
  Health AI/Cancer-Prediction/models.pkl
  Health AI/Cancer-Prediction/requirements.txt
Labels: SSOC S4, ADVANCED

#53 Pull request of GDP Prediction Model
  Financial AI/GDP Prediction/Readme.md
  Financial AI/GDP Prediction/gdp-prediction-model.ipynb
Labels: SSOC S4, INTERMEDIATE

#62 Add Mental Health Prediction ML Model using Survey Data (#9)
  Health AI/Student-Health-Predictor/MentalHealthPredictionUsingMachineLearningAlgorithms.ipynb
  Health AI/Student-Health-Predictor/README.md
  Health AI/Student-Health-Predictor/survey.csv
Labels: SSOC S4, INTERMEDIATE

#80 Enhanced readme #79
  README.md
Labels: documentation, enhancement, good first issue, SSOC S4, BEGINNER

#82 🚀 Enhanced Bidirectional LSTM: GPU Acceleration & Advanced Features
  Bidirectional LSTM/Models/bidirectional-lstm.ipynb
  Bidirectional LSTM/Models/my_best_model.epoch05-loss0.00.hdf5
  Bidirectional LSTM/Models/temperature-prediction-using-bidirectional-lstm.ipynb
  Bidirectional LSTM/README.md
Labels: SSOC S4, INTERMEDIATE

#87 Startup success analyser
  Financial AI/startup success predictor/README.md
  Financial AI/startup success predictor/app.py
  Financial AI/startup success predictor/assets/image.png
  Financial AI/startup success predictor/data/g.py
  Financial AI/startup success predictor/data/raw/startup data.csv
  Financial AI/startup success predictor/models/rf_model.pkl
  Financial AI/startup success predictor/requirements.txt
  Financial AI/startup success predictor/src/predict.py
  Financial AI/startup success predictor/src/preprocess.py
  Financial AI/startup success predictor/src/train_model.py
Labels: SSOC S4, INTERMEDIATE

#126 UI arima currency forecasting
  src/Financial Analysis/Business Analytics/startup success predictor/data/startup data.csv
  src/Financial Analysis/Business Analytics/startup success predictor/predict.py
  src/Financial Analysis/Business Analytics/startup success predictor/preprocess.py
  src/Financial Analysis/Business Analytics/startup success predictor/train_model.py
  src/Financial Analysis/Market Analysis/Market Rate Analysis/README.md
  src/Financial Analysis/Market Analysis/Market Rate Analysis/asstes/euro arima.jpeg
  src/Financial Analysis/Market Analysis/Market Rate Analysis/asstes/euro arima_g.png
  src/Financial Analysis/Market Analysis/Market Rate Analysis/asstes/indian.jpeg
  src/Financial Analysis/Market Analysis/Market Rate Analysis/asstes/indian_g.png
  src/Financial Analysis/Market Analysis/Market Rate Analysis/asstes/inr lstm.jpeg
  src/Financial Analysis/Market Analysis/Market Rate Analysis/asstes/inr lstm_g.png
  src/Financial Analysis/Market Analysis/Market Rate Analysis/main.py
Labels: SSOC S4, INTERMEDIATE

#136 Pull request of Google Teachable Machine
  src/Machine Learning Techniques/Google Teachable Machine/Deployment/deploy_model.html
  src/Machine Learning Techniques/Google Teachable Machine/Deployment/deploy_model_p5.html
  src/Machine Learning Techniques/Google Teachable Machine/Model/google_teachable_machine.ipynb
  src/Machine Learning Techniques/Google Teachable Machine/Model/model_application.py
  src/Machine Learning Techniques/Google Teachable Machine/README.md
  src/Machine Learning Techniques/Google Teachable Machine/images/keras_model.png
  src/Machine Learning Techniques/Google Teachable Machine/images/keras_model_sequenial3.png
  src/Machine Learning Techniques/Google Teachable Machine/images/keras_model_sequential1.png
  src/Machine Learning Techniques/Google Teachable Machine/images/keras_model_sequential1_model.svg
Labels: SSOC S4, INTERMEDIATE

#134 Employee attrition prediction
  src/Agricultural Solutions/Soil Classifier CNN/images/training_plot.png
  src/Agricultural Solutions/Soil Classifier CNN/requirements.txt
  src/Financial Analysis/Business Analytics/Employee-Attrition-Prediction/README.md
  src/Financial Analysis/Business Analytics/Employee-Attrition-Prediction/assets/image.png
  src/Financial Analysis/Business Analytics/Employee-Attrition-Prediction/catboost_info/catboost_training.json
  src/Financial Analysis/Business Analytics/Employee-Attrition-Prediction/catboost_info/learn/events.out.tfevents
  src/Financial Analysis/Business Analytics/Employee-Attrition-Prediction/catboost_info/learn_error.tsv
  src/Financial Analysis/Business Analytics/Employee-Attrition-Prediction/catboost_info/time_left.tsv
  src/Financial Analysis/Business Analytics/Employee-Attrition-Prediction/data/employee_attrition.csv
  src/Financial Analysis/Business Analytics/Employee-Attrition-Prediction/predict.py
  src/Financial Analysis/Business Analytics/Employee-Attrition-Prediction/train.py
Labels: SSOC S4, INTERMEDIATE

#132 Loan prediction
  src/Financial Analysis/Market Analysis/Loan prediction/README.md
  src/Financial Analysis/Market Analysis/Loan prediction/assets/image.png
  src/Financial Analysis/Market Analysis/Loan prediction/data/loan_train.csv
  src/Financial Analysis/Market Analysis/Loan prediction/models/train_columns.txt
  src/Financial Analysis/Market Analysis/Loan prediction/predict.py
  src/Financial Analysis/Market Analysis/Loan prediction/preprocess.py
  src/Financial Analysis/Market Analysis/Loan prediction/train.py
Labels: SSOC S4, INTERMEDIATE

#140 Stroke prediction
  .gitignore
  src/Healthcare/Health Monitoring/stroke-prediction/README.md
  src/Healthcare/Health Monitoring/stroke-prediction/assets/image.png
  src/Healthcare/Health Monitoring/stroke-prediction/data/stroke_data.csv
  src/Healthcare/Health Monitoring/stroke-prediction/predict.py
  src/Healthcare/Health Monitoring/stroke-prediction/preprocess.py
  src/Healthcare/Health Monitoring/stroke-prediction/train.py
Labels: SSOC S4, INTERMEDIATE

#154 ui-crop-recommender
  src/Agricultural Solutions/Crop Recommendation System/README.md
  src/Agricultural Solutions/Crop Recommendation System/app.py
  src/Agricultural Solutions/Crop Recommendation System/assets/cofee.jpeg
  src/Agricultural Solutions/Crop Recommendation System/assets/rice.jpeg
  src/Agricultural Solutions/Crop Recommendation System/predict.py
Labels: SSOC S4, INTERMEDIATE

#156 UI fertiliser recommender
  src/Agricultural Solutions/Fertiliser Recommendation System/README.md
  src/Agricultural Solutions/Fertiliser Recommendation System/assets/1.jpeg
  src/Agricultural Solutions/Fertiliser Recommendation System/assets/2.jpeg
  src/Agricultural Solutions/Fertiliser Recommendation System/src/predict.py
Labels: SSOC S4, INTERMEDIATE

#165 Bitcoin
  src/Financial Analysis/Cryptocurrency/Bitcoin Price Prediction/.gitignore
  src/Financial Analysis/Cryptocurrency/Bitcoin Price Prediction/Bitcoin_Price_Prediction.ipynb
Labels: SSOC S4, BEGINNER

#168 Pull request of Plant Seedlings Classification
  src/Agricultural Solutions/Plant Seedlings Classification/Dataset/README.md
  src/Agricultural Solutions/Plant Seedlings Classification/Images/plant1.jpg
  src/Agricultural Solutions/Plant Seedlings Classification/Images/plant2.png
  src/Agricultural Solutions/Plant Seedlings Classification/Model/Plant_seedlings_classification.ipynb
  src/Agricultural Solutions/Plant Seedlings Classification/README.md
  src/Agricultural Solutions/Plant Seedlings Classification/requirements.txt
Labels: SSOC S4, INTERMEDIATE

#170 Pull request of Random Forest Test
  src/Machine Learning Techniques/Random forest test/README.md
  src/Machine Learning Techniques/Random forest test/random_fore.ipynb
  src/Machine Learning Techniques/Random forest test/random_forest.ipynb
Labels: SSOC S4, INTERMEDIATE
